{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stolon.fullname" . }}-exporter
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "stolon.fullname" . }}-exporter
  podManagementPolicy: Parallel
  replicas: {{ .Values.keeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stolon.name" . }}
      release: {{ .Release.Name }}
      component: stolon-exporter
  template:
    metadata:
      labels:
        app: {{ template "stolon.name" . }}
        release: {{ .Release.Name }}
        component: stolon-exporter
        stolon-cluster: {{ template "stolon.fullname" . }}
{{- with .Values.exporter.podLabels }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/exporter-configmap.yaml") . | sha256sum }}
{{- with .Values.exporter.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - "--extend.query-path=/etc/config.yaml"
          {{- if .Values.exporter.config.disableDefaultMetrics }}
          - "--disable-default-metrics"
          {{- end }}
          {{- if .Values.exporter.config.disableSettingsMetrics }}
          - "--disable-settings-metrics"
          {{- end }}
          {{- if .Values.exporter.config.autoDiscoverDatabases }}
          - "--auto-discover-databases"
          {{- if .Values.exporter.config.excludeDatabases }}
          - "--exclude-databases"
          - {{ .Values.exporter.config.excludeDatabases | join "," }}
          {{- end }}
          {{- end }}
          command:
            - /bin/bash
            - -c
            - |
              set -ex
              IFS='-' read -ra ADDR <<< "${POD_NAME}"
              export DATA_SOURCE_URI={{ template "stolon.fullname" . }}-keeper-${ADDR[-1]}.{{ template "stolon.fullname" . }}-keeper-headless:5432/postgres?sslmode=disable
              exec postgres_exporter
          env:
          - name: DATA_SOURCE_USER
            value: {{ .Values.superuserUsername | quote }}
          - name: DATA_SOURCE_PASS
            value: {{ .Values.superuserPassword | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.exporter.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.exporter.resources | indent 12 }}
          volumeMounts:
            - name: queries
              mountPath: /etc/config.yaml
              subPath: config.yaml
      securityContext:
{{ toYaml .Values.exporter.securityContext | indent 8 }}
     {{- with .Values.exporter.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.exporter.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.exporter.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ template "stolon.fullname" . }}-exporter
        name: queries
{{- end }}
