{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.fullname" . }}-exporter-headless
  {{- if .Values.exporter.service.annotations }}
  annotations:
{{ toYaml .Values.exporter.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template  "stolon.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.exporter.service.labels }}
{{ toYaml .Values.exporter.service.labels | trim | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: {{ .Values.exporter.service.targetPort }}
      protocol: TCP
      name: {{ .Values.exporter.service.name }}
  selector:
    app: {{ template "stolon.name" . }}
    release: {{ .Release.Name }}
    component: stolon-exporter
  {{- end }}
